spring:
  datasource:
    username: root
    password: cHJvbWV0aGV1cw==
    url: jdbc:mysql://localhost:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true